### PR TITLE
Update Ungoogled Chromium to 146.0.7680.80-1

### PR DESCRIPTION
**Pull request by rany2**

### CODE REVIEW

**Comment by rany2** [comment]
bot, build

**Comment by rany2** [comment]
bot, build

**Comment by Erick555** [comment]
> Interesting, I had the same issue with
> 
> ```
> ../../net/http/http_auth_gssapi_posix.h:26:10: fatal error: 'gssapi.h' file not found
>    26 | #include <gssapi.h>
> ```
> 
> when I tried to build this flatpak recently on my machine (arm64). I was only able to solve it by adding
> 
> ```
> flags+=('use_kerberos = false')
> ```
> 
> to `build-aux/build.sh`, but I assume that's not the proper solution.

@rany2 this is actually regression introduced in baseapp with https://github.com/flathub/org.chromium.Chromium.BaseApp/commit/de3194b6768da0d6ef5ec4d41ab47638f8aca4c9

when it will be reverted you could drop kerberos build from manifest

**Comment by rany2** [comment]
Ah, thanks @Erick555.. I see they removed the Kerberos headers. I might want to drop the BaseApp so I can have better control over my dependencies. Unfortunately, regular Chromium does not use the BaseApp. I mainly switched to the BaseApp thinking regular Chromium will do the same but it seems that never happened.

**Comment by Erick555** [comment]
@rany2 regular chromium surely [use the baseapp](https://github.com/flathub/org.chromium.Chromium/blob/master/org.chromium.Chromium.yaml#L5) since [2022](https://github.com/flathub/org.chromium.Chromium/commit/b09343ec46c88439eacadb0f5e6fb2df1b2e721e). In fact I found this issue because it blocks regular chromium update to 25.08 runtime which was previously blocked on something else (this is the reason I found it only now instead of few months ago)

**Comment by Erick555** [comment]
Kerberos headers are restored in baseapp now so if you decide to keep using baseapp you may remove kerbreos build from manifest in next update

**Comment by rany2** [comment]
Thanks for the heads up, for now I'll just keep using the BaseApp. It's neater than managing those dependencies myself. It would be nice if vanilla Chromium made the jump too though
